### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by wwhai** [mttsner/luautil#3]
## Position
At `func (f *Function) Chunk() (chunk ast.Chunk)`:
```go
func (f *Function) Chunk() (chunk ast.Chunk) {
	root := f.Blocks[0]
	return root.ToAst()
}
```
It seems Missing `domFrontier`.

## Detail
` root.ToAst()` define ：
```go
func (b *BasicBlock) ToAst(dom domFrontier) (chunk ast.Chunk)
```

**Comment by mttsner** [comment]
Yeah the SSA implementation is very incomplete at the moment, I would disregard it for the time being.
Moreover, a lot of the newer SSA implementation is on the ssa branch and everything on the main branch is outdated.
Furthermore, I have been working on SSA recently so if you're interested in using it I could work on publishing the most up-to-date version or I could just prune it from the main branch so it doesn't throw errors for the time being.

**Comment by wwhai** [comment]
> Yeah the SSA implementation is very incomplete at the moment, I would disregard it for the time being. Moreover, a lot of the newer SSA implementation is on the ssa branch and everything on the main branch is outdated. Furthermore, I have been working on SSA recently so if you're interested in using it I could work on publishing the most up-to-date version or I could just prune it from the main branch so it doesn't throw errors for the time being.

Thanks, But I only use this repository to format my lua source text

**Comment by mttsner** [comment]
I've removed the ssa package from the latest release [v1.4.12](https://github.com/mttsner/luautil/releases/tag/v1.4.12).
